"""Generate the compact native SV600 color table from ScanSnap Home data.

The Windows worker reads 17^3 RGB control points from
``CscLutTbl_SV600.csv`` and expands them to a 48 MiB 256^3 table with
three-stage integer trilinear interpolation.  The Linux backend keeps only
the 14,739 output bytes and performs that same interpolation per pixel.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import pathlib


EXPECTED_SOURCE_SHA256 = (
    "2ac4e6bf6779a4f05a67359c0eeb0bd72d3921a6330a9904059f5ad996dc14d9"
)
GRID_POINTS = 17 * 17 * 17


def gamma_table() -> list[int]:
    return [round(255.0 * ((value / 255.0) ** (1.0 / 1.8))) for value in range(256)]


def read_grid(path: pathlib.Path) -> list[tuple[int, int, int]]:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != EXPECTED_SOURCE_SHA256:
        raise SystemExit(
            f"unexpected source SHA-256 {digest}; expected {EXPECTED_SOURCE_SHA256}"
        )

    rows: list[tuple[int, int, int]] = []
    with path.open(newline="", encoding="ascii") as stream:
        for line_number, fields in enumerate(csv.reader(stream), 1):
            if len(fields) != 6:
                raise SystemExit(f"line {line_number}: expected six CSV fields")
            values = tuple(int(field) for field in fields)
            if any(value < 0 or value > 255 for value in values):
                raise SystemExit(f"line {line_number}: byte outside 0..255")
            expected_index = len(rows)
            expected_input = (
                (expected_index // (17 * 17)) * 16,
                ((expected_index // 17) % 17) * 16,
                (expected_index % 17) * 16,
            )
            expected_input = tuple(min(value, 255) for value in expected_input)
            if values[:3] != expected_input:
                raise SystemExit(
                    f"line {line_number}: input {values[:3]} != {expected_input}"
                )
            rows.append(values[3:])
    if len(rows) != GRID_POINTS:
        raise SystemExit(f"expected {GRID_POINTS} rows, found {len(rows)}")
    return rows


def emit_array(name: str, values: list[int], width: int = 16) -> list[str]:
    lines = [f"static const unsigned char {name}[{len(values)}] = {{"]
    for offset in range(0, len(values), width):
        chunk = ", ".join(str(value) for value in values[offset : offset + width])
        lines.append(f"  {chunk},")
    lines.append("};")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_csv", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    grid = read_grid(args.source_csv)
    flattened = [channel for point in grid for channel in point]
    grid_digest = hashlib.sha256(bytes(flattened)).hexdigest()
    lines = [
        "/* Generated from the numeric SV600 17x17x17 color control grid.",
        f" * Source SHA-256: {EXPECTED_SOURCE_SHA256}",
        f" * Packed grid SHA-256: {grid_digest}",
        " * Generated by tools/windows/generate_sv600_srgb_lut.py. */",
        "",
        *emit_array("sv600_gamma_10_to_18", gamma_table()),
        "",
        *emit_array("sv600_srgb_grid", flattened, width=18),
        "",
    ]
    args.output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
