#!/bin/sh
set -eu

backend_dir=/usr/lib/x86_64-linux-gnu/sane
ln -sfn libsane-sv600-fujitsu.so.1 "$backend_dir/libsane-fujitsu.so.1"

if command -v udevadm >/dev/null 2>&1; then
    udevadm control --reload-rules || true
    udevadm trigger --subsystem-match=usb --attr-match=idVendor=04c5 \
        --attr-match=idProduct=128e || true
    udevadm trigger --subsystem-match=usb --attr-match=idVendor=04c5 \
        --attr-match=idProduct=13ba || true
fi

exit 0
